version: '3.8'

services:
  # PostgreSQL database for development
  postgres:
    image: postgres:15-alpine
    container_name: vayovault-postgres
    environment:
      POSTGRES_DB: vayovault_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    networks:
      - vayovault-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d vayovault_dev"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    container_name: vayovault-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - vayovault-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Commander for Redis GUI (development only)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: vayovault-redis-commander
    environment:
      REDIS_HOSTS: local:vayovault-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - vayovault-network
    profiles:
      - dev-tools

  # Mailhog for email testing (development only)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: vayovault-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - vayovault-network
    profiles:
      - dev-tools

  # Next.js application (for containerized development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vayovault-app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://developer:dev_password@postgres:5432/vayovault_dev
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development-secret-key
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vayovault-network
    profiles:
      - full-stack

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  vayovault-network:
    driver: bridge